[rospy.client][INFO] 2022-05-20 22:58:49,698: init_node, name[/turtle1_tf_broadcaster], pid[3472]
[xmlrpc][INFO] 2022-05-20 22:58:49,699: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2022-05-20 22:58:49,699: Started XML-RPC server [http://ubuntu:43921/]
[rospy.impl.masterslave][INFO] 2022-05-20 22:58:49,699: _ready: http://ubuntu:43921/
[rospy.registration][INFO] 2022-05-20 22:58:49,700: Registering with master node http://localhost:11311
[xmlrpc][INFO] 2022-05-20 22:58:49,701: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2022-05-20 22:58:49,701: ROS Slave URI: [http://ubuntu:43921/]
[rospy.init][INFO] 2022-05-20 22:58:49,702: registered with master
[rospy.rosout][INFO] 2022-05-20 22:58:49,702: initializing /rosout core topic
[rospy.rosout][INFO] 2022-05-20 22:58:49,707: connected to core topic /rosout
[rospy.simtime][INFO] 2022-05-20 22:58:49,710: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2022-05-20 22:58:49,737: topic[/turtle1/pose] adding connection to [http://ubuntu:46331/], count 0
[rospy.internal][INFO] 2022-05-20 22:58:49,843: topic[/tf] adding connection to [/turtle_pointer], count 0
[rospy.internal][INFO] 2022-05-20 22:58:49,944: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][ERROR] 2022-05-20 23:01:35,660: Unable to initiate TCP/IP socket to ubuntu:50801 (http://ubuntu:46331/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 558, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 651, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 594, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/turtle1/pose] from [TCPROS connection on port 50801 to [127.0.0.1:45500 on socket 28]] [/turtle1_tf_broadcaster].

[rospy.internal][WARNING] 2022-05-20 23:01:36,663: Unknown error initiating TCP/IP socket to ubuntu:50801 (http://ubuntu:46331/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 556, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2022-05-20 23:01:36,663: topic[/turtle1/pose] removing connection to http://ubuntu:46331/
[rospy.core][INFO] 2022-05-20 23:01:42,798: signal_shutdown [signal-2]
[rospy.internal][INFO] 2022-05-20 23:01:42,806: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2022-05-20 23:01:42,806: topic[/tf] removing connection to /turtle_pointer
[rospy.impl.masterslave][INFO] 2022-05-20 23:01:42,807: signal-2
[rospy.core][INFO] 2022-05-20 23:01:42,944: signal_shutdown [atexit]
