[rospy.client][INFO] 2022-04-02 23:55:04,636: init_node, name[/robot_teleop], pid[24417]
[xmlrpc][INFO] 2022-04-02 23:55:04,637: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2022-04-02 23:55:04,637: Started XML-RPC server [http://ubuntu:45379/]
[rospy.impl.masterslave][INFO] 2022-04-02 23:55:04,637: _ready: http://ubuntu:45379/
[rospy.init][INFO] 2022-04-02 23:55:04,638: ROS Slave URI: [http://ubuntu:45379/]
[xmlrpc][INFO] 2022-04-02 23:55:04,640: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2022-04-02 23:55:04,643: Registering with master node http://localhost:11311
[rospy.init][INFO] 2022-04-02 23:55:04,738: registered with master
[rospy.rosout][INFO] 2022-04-02 23:55:04,739: initializing /rosout core topic
[rospy.rosout][INFO] 2022-04-02 23:55:04,744: connected to core topic /rosout
[rospy.simtime][INFO] 2022-04-02 23:55:04,750: initializing /clock core topic
[rospy.simtime][INFO] 2022-04-02 23:55:04,759: connected to core topic /clock
[rospy.internal][INFO] 2022-04-02 23:55:04,773: topic[/clock] adding connection to [http://ubuntu:33685/], count 0
[rospy.internal][INFO] 2022-04-02 23:55:04,961: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2022-04-02 23:55:05,063: topic[/cmd_vel_mux/input/teleop] adding connection to [/mobile_base_nodelet_manager], count 0
[rospy.client][INFO] 2022-04-03 15:27:29,982: init_node, name[/robot_teleop], pid[8179]
[xmlrpc][INFO] 2022-04-03 15:27:29,984: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2022-04-03 15:27:29,989: Started XML-RPC server [http://ubuntu:40323/]
[rospy.init][INFO] 2022-04-03 15:27:29,990: ROS Slave URI: [http://ubuntu:40323/]
[rospy.impl.masterslave][INFO] 2022-04-03 15:27:29,990: _ready: http://ubuntu:40323/
[xmlrpc][INFO] 2022-04-03 15:27:29,991: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2022-04-03 15:27:29,993: Registering with master node http://localhost:11311
[rospy.init][INFO] 2022-04-03 15:27:30,091: registered with master
[rospy.rosout][INFO] 2022-04-03 15:27:30,092: initializing /rosout core topic
[rospy.rosout][INFO] 2022-04-03 15:27:30,098: connected to core topic /rosout
[rospy.simtime][INFO] 2022-04-03 15:27:30,104: initializing /clock core topic
[rospy.simtime][INFO] 2022-04-03 15:27:30,109: connected to core topic /clock
[rospy.internal][INFO] 2022-04-03 15:27:30,127: topic[/clock] adding connection to [http://ubuntu:34653/], count 0
[rospy.internal][INFO] 2022-04-03 15:27:30,308: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2022-04-03 15:27:30,353: topic[/cmd_vel_mux/input/teleop] adding connection to [/mobile_base_nodelet_manager], count 0
[rospy.internal][INFO] 2022-04-03 15:29:16,344: topic[/cmd_vel_mux/input/teleop] removing connection to /mobile_base_nodelet_manager
[rospy.internal][ERROR] 2022-04-03 15:29:16,441: Unable to initiate TCP/IP socket to ubuntu:34273 (http://ubuntu:34653/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 558, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 651, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 594, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 34273 to [127.0.0.1:36716 on socket 19]] [/robot_teleop].

[rospy.internal][ERROR] 2022-04-03 15:29:17,445: Unable to initiate TCP/IP socket to ubuntu:34273 (http://ubuntu:34653/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 558, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 651, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 594, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 34273 to [127.0.0.1:36800 on socket 17]] [/robot_teleop].

[rospy.internal][ERROR] 2022-04-03 15:29:19,449: Unable to initiate TCP/IP socket to ubuntu:34273 (http://ubuntu:34653/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 558, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 651, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 594, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 34273 to [127.0.0.1:36802 on socket 17]] [/robot_teleop].

[rospy.client][INFO] 2022-04-03 22:59:54,450: init_node, name[/robot_teleop], pid[2684]
[xmlrpc][INFO] 2022-04-03 22:59:54,453: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2022-04-03 22:59:54,454: Started XML-RPC server [http://ubuntu:44997/]
[rospy.impl.masterslave][INFO] 2022-04-03 22:59:54,454: _ready: http://ubuntu:44997/
[rospy.init][INFO] 2022-04-03 22:59:54,454: ROS Slave URI: [http://ubuntu:44997/]
[rospy.registration][INFO] 2022-04-03 22:59:54,455: Registering with master node http://localhost:11311
[xmlrpc][INFO] 2022-04-03 22:59:54,455: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2022-04-03 22:59:54,555: registered with master
[rospy.rosout][INFO] 2022-04-03 22:59:54,556: initializing /rosout core topic
[rospy.rosout][INFO] 2022-04-03 22:59:54,560: connected to core topic /rosout
[rospy.simtime][INFO] 2022-04-03 22:59:54,562: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2022-04-03 22:59:54,810: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2022-04-03 23:01:12,576: topic[/rosout] removing connection to /rosout
